.include "../Makefile.inc"

.PATH:	${S}/fs/msfs

KMOD=		msfs

SRCS=bs_access.c
SRCS+=bs_bitfile_sets.c
SRCS+=bs_bmt_util.c
SRCS+=bs_buffer2.c
SRCS+=bs_copy.c
SRCS+=bs_create.c
SRCS+=bs_delete.c
SRCS+=bs_domain.c
SRCS+=bs_errlst.c
SRCS+=bs_extents.c
SRCS+=bs_freeze.c
SRCS+=bs_index.c
SRCS+=bs_init.c
SRCS+=bs_inmem_map.c
SRCS+=bs_migrate.c
SRCS+=bs_misc.c
SRCS+=bs_msg_queue.c
SRCS+=bs_params.c
SRCS+=bs_qio.c
SRCS+=bs_sbm.c
SRCS+=bs_service_class.c
SRCS+=bs_stg.c
SRCS+=bs_stripe.c
SRCS+=bs_tagdir.c
SRCS+=fs_create.c
SRCS+=fs_dir_init.c
SRCS+=fs_dir_lookup.c
SRCS+=fs_file_sets.c
SRCS+=fs_read_write.c
SRCS+=ftx_recovery.c
SRCS+=ftx_routines.c
SRCS+=ms_generic_locks.c
SRCS+=ms_logger.c
SRCS+=ms_mode.c
SRCS+=ms_privates.c
SRCS+=ms_public.c
SRCS+=msfs_cfg.c
SRCS+=msfs_config.c
SRCS+=msfs_io.c
SRCS+=msfs_lookup.c
SRCS+=msfs_misc.c
SRCS+=msfs_proplist.c
SRCS+=msfs_syscalls.c
SRCS+=msfs_vfsops.c
SRCS+=msfs_vnops.c
SRCS+=vfast.c

.include <bsd.kmodule.mk>
