INCSDIR= /usr/include/fs/msfs

# Missing: advfs_evm.h

INCS = advfs_modules.h bs_access.h bs_bitfile_sets.h bs_bmt.h bs_buf.h bs_copy.h bs_delete.h bs_domain.h bs_error.h bs_extents.h bs_freeze.h bs_ims.h bs_index.h bs_inmem_map.h bs_migrate.h bs_msg_queue.h bs_ods.h bs_params.h bs_public.h bs_sbm.h bs_service_classes.h bs_stg.h bs_stripe.h bs_tagdir.h bs_vd.h dirmfs.h fs_dir.h fs_dir_routines.h fs_file_sets.h fs_quota.h ftx_agents.h ftx_privates.h ftx_public.h ms_assert.h ms_generic_locks.h ms_logger.h ms_osf.h ms_privates.h ms_public.h msfs_syscalls.h osf_file.h vfast.h

.include <bsd.kinc.mk>
